package com.merck.catalog.admin.vo;

import java.util.Date;

public class TbCab004d {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.BOARD_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String boardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.POST_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.MANG_REG_NO
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String mangRegNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.MANG_DEPT_NM
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String mangDeptNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.MANG_USR_NM
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String mangUsrNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.EMAIL_ADDR
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String emailAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.COMP_TEL_NO
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String compTelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.PHONE_NO
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.REGIST_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String registUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.REGIST_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.UPDT_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String updtUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAB004D.UPDT_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private Date updtDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.BOARD_ID
     *
     * @return the value of TB_CAB004D.BOARD_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.BOARD_ID
     *
     * @param boardId the value for TB_CAB004D.BOARD_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setBoardId(String boardId) {
        this.boardId = boardId == null ? null : boardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.POST_ID
     *
     * @return the value of TB_CAB004D.POST_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.POST_ID
     *
     * @param postId the value for TB_CAB004D.POST_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setPostId(String postId) {
        this.postId = postId == null ? null : postId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.MANG_REG_NO
     *
     * @return the value of TB_CAB004D.MANG_REG_NO
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getMangRegNo() {
        return mangRegNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.MANG_REG_NO
     *
     * @param mangRegNo the value for TB_CAB004D.MANG_REG_NO
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setMangRegNo(String mangRegNo) {
        this.mangRegNo = mangRegNo == null ? null : mangRegNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.MANG_DEPT_NM
     *
     * @return the value of TB_CAB004D.MANG_DEPT_NM
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getMangDeptNm() {
        return mangDeptNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.MANG_DEPT_NM
     *
     * @param mangDeptNm the value for TB_CAB004D.MANG_DEPT_NM
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setMangDeptNm(String mangDeptNm) {
        this.mangDeptNm = mangDeptNm == null ? null : mangDeptNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.MANG_USR_NM
     *
     * @return the value of TB_CAB004D.MANG_USR_NM
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getMangUsrNm() {
        return mangUsrNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.MANG_USR_NM
     *
     * @param mangUsrNm the value for TB_CAB004D.MANG_USR_NM
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setMangUsrNm(String mangUsrNm) {
        this.mangUsrNm = mangUsrNm == null ? null : mangUsrNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.EMAIL_ADDR
     *
     * @return the value of TB_CAB004D.EMAIL_ADDR
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getEmailAddr() {
        return emailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.EMAIL_ADDR
     *
     * @param emailAddr the value for TB_CAB004D.EMAIL_ADDR
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setEmailAddr(String emailAddr) {
        this.emailAddr = emailAddr == null ? null : emailAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.COMP_TEL_NO
     *
     * @return the value of TB_CAB004D.COMP_TEL_NO
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getCompTelNo() {
        return compTelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.COMP_TEL_NO
     *
     * @param compTelNo the value for TB_CAB004D.COMP_TEL_NO
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setCompTelNo(String compTelNo) {
        this.compTelNo = compTelNo == null ? null : compTelNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.PHONE_NO
     *
     * @return the value of TB_CAB004D.PHONE_NO
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.PHONE_NO
     *
     * @param phoneNo the value for TB_CAB004D.PHONE_NO
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.REGIST_USR_ID
     *
     * @return the value of TB_CAB004D.REGIST_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getRegistUsrId() {
        return registUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.REGIST_USR_ID
     *
     * @param registUsrId the value for TB_CAB004D.REGIST_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setRegistUsrId(String registUsrId) {
        this.registUsrId = registUsrId == null ? null : registUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.REGIST_DT
     *
     * @return the value of TB_CAB004D.REGIST_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.REGIST_DT
     *
     * @param registDt the value for TB_CAB004D.REGIST_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.UPDT_USR_ID
     *
     * @return the value of TB_CAB004D.UPDT_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getUpdtUsrId() {
        return updtUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.UPDT_USR_ID
     *
     * @param updtUsrId the value for TB_CAB004D.UPDT_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setUpdtUsrId(String updtUsrId) {
        this.updtUsrId = updtUsrId == null ? null : updtUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAB004D.UPDT_DT
     *
     * @return the value of TB_CAB004D.UPDT_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public Date getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAB004D.UPDT_DT
     *
     * @param updtDt the value for TB_CAB004D.UPDT_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }
}