package com.merck.catalog.admin.vo;

import java.util.Date;

public class TbCac001d {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAC001D.BOARD_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String boardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAC001D.POST_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAC001D.PUSH_REG_NO
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String pushRegNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAC001D.CATLG_URL
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String catlgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAC001D.PUSH_BEGIN_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String pushBeginDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAC001D.PUSH_END_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String pushEndDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAC001D.MANG_ITEM_VAL_01
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String mangItemVal01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAC001D.MANG_ITEM_VAL_02
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String mangItemVal02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAC001D.MANG_ITEM_VAL_03
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String mangItemVal03;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAC001D.DEL_YN
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String delYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAC001D.REGIST_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String registUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAC001D.REGIST_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAC001D.UPDT_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String updtUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CAC001D.UPDT_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private Date updtDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAC001D.BOARD_ID
     *
     * @return the value of TB_CAC001D.BOARD_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAC001D.BOARD_ID
     *
     * @param boardId the value for TB_CAC001D.BOARD_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setBoardId(String boardId) {
        this.boardId = boardId == null ? null : boardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAC001D.POST_ID
     *
     * @return the value of TB_CAC001D.POST_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAC001D.POST_ID
     *
     * @param postId the value for TB_CAC001D.POST_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setPostId(String postId) {
        this.postId = postId == null ? null : postId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAC001D.PUSH_REG_NO
     *
     * @return the value of TB_CAC001D.PUSH_REG_NO
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getPushRegNo() {
        return pushRegNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAC001D.PUSH_REG_NO
     *
     * @param pushRegNo the value for TB_CAC001D.PUSH_REG_NO
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setPushRegNo(String pushRegNo) {
        this.pushRegNo = pushRegNo == null ? null : pushRegNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAC001D.CATLG_URL
     *
     * @return the value of TB_CAC001D.CATLG_URL
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getCatlgUrl() {
        return catlgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAC001D.CATLG_URL
     *
     * @param catlgUrl the value for TB_CAC001D.CATLG_URL
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setCatlgUrl(String catlgUrl) {
        this.catlgUrl = catlgUrl == null ? null : catlgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAC001D.PUSH_BEGIN_DT
     *
     * @return the value of TB_CAC001D.PUSH_BEGIN_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getPushBeginDt() {
        return pushBeginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAC001D.PUSH_BEGIN_DT
     *
     * @param pushBeginDt the value for TB_CAC001D.PUSH_BEGIN_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setPushBeginDt(String pushBeginDt) {
        this.pushBeginDt = pushBeginDt == null ? null : pushBeginDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAC001D.PUSH_END_DT
     *
     * @return the value of TB_CAC001D.PUSH_END_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getPushEndDt() {
        return pushEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAC001D.PUSH_END_DT
     *
     * @param pushEndDt the value for TB_CAC001D.PUSH_END_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setPushEndDt(String pushEndDt) {
        this.pushEndDt = pushEndDt == null ? null : pushEndDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAC001D.MANG_ITEM_VAL_01
     *
     * @return the value of TB_CAC001D.MANG_ITEM_VAL_01
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getMangItemVal01() {
        return mangItemVal01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAC001D.MANG_ITEM_VAL_01
     *
     * @param mangItemVal01 the value for TB_CAC001D.MANG_ITEM_VAL_01
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setMangItemVal01(String mangItemVal01) {
        this.mangItemVal01 = mangItemVal01 == null ? null : mangItemVal01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAC001D.MANG_ITEM_VAL_02
     *
     * @return the value of TB_CAC001D.MANG_ITEM_VAL_02
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getMangItemVal02() {
        return mangItemVal02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAC001D.MANG_ITEM_VAL_02
     *
     * @param mangItemVal02 the value for TB_CAC001D.MANG_ITEM_VAL_02
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setMangItemVal02(String mangItemVal02) {
        this.mangItemVal02 = mangItemVal02 == null ? null : mangItemVal02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAC001D.MANG_ITEM_VAL_03
     *
     * @return the value of TB_CAC001D.MANG_ITEM_VAL_03
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getMangItemVal03() {
        return mangItemVal03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAC001D.MANG_ITEM_VAL_03
     *
     * @param mangItemVal03 the value for TB_CAC001D.MANG_ITEM_VAL_03
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setMangItemVal03(String mangItemVal03) {
        this.mangItemVal03 = mangItemVal03 == null ? null : mangItemVal03.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAC001D.DEL_YN
     *
     * @return the value of TB_CAC001D.DEL_YN
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getDelYn() {
        return delYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAC001D.DEL_YN
     *
     * @param delYn the value for TB_CAC001D.DEL_YN
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setDelYn(String delYn) {
        this.delYn = delYn == null ? null : delYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAC001D.REGIST_USR_ID
     *
     * @return the value of TB_CAC001D.REGIST_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getRegistUsrId() {
        return registUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAC001D.REGIST_USR_ID
     *
     * @param registUsrId the value for TB_CAC001D.REGIST_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setRegistUsrId(String registUsrId) {
        this.registUsrId = registUsrId == null ? null : registUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAC001D.REGIST_DT
     *
     * @return the value of TB_CAC001D.REGIST_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAC001D.REGIST_DT
     *
     * @param registDt the value for TB_CAC001D.REGIST_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAC001D.UPDT_USR_ID
     *
     * @return the value of TB_CAC001D.UPDT_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getUpdtUsrId() {
        return updtUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAC001D.UPDT_USR_ID
     *
     * @param updtUsrId the value for TB_CAC001D.UPDT_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setUpdtUsrId(String updtUsrId) {
        this.updtUsrId = updtUsrId == null ? null : updtUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CAC001D.UPDT_DT
     *
     * @return the value of TB_CAC001D.UPDT_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public Date getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CAC001D.UPDT_DT
     *
     * @param updtDt the value for TB_CAC001D.UPDT_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }
}