package com.merck.catalog.admin.vo;

import java.util.Date;

public class TbSaf002d {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF002D.IMG_FILE_GRP_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String imgFileGrpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF002D.IMG_FILE_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String imgFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF002D.FILE_NM
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String fileNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF002D.FILE_EXT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String fileExt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF002D.FILE_LENTH
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private Long fileLenth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF002D.FILE_PATH
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF002D.FILE_URL
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF002D.THMNL_IMG_YN
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String thmnlImgYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF002D.SORT_SN
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private Long sortSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF002D.REGIST_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String registUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF002D.REGIST_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF002D.UPDT_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private String updtUsrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF002D.UPDT_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private Date updtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SAF002D.FILE_BLOB
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    private byte[] fileBlob;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF002D.IMG_FILE_GRP_ID
     *
     * @return the value of TB_SAF002D.IMG_FILE_GRP_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getImgFileGrpId() {
        return imgFileGrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF002D.IMG_FILE_GRP_ID
     *
     * @param imgFileGrpId the value for TB_SAF002D.IMG_FILE_GRP_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setImgFileGrpId(String imgFileGrpId) {
        this.imgFileGrpId = imgFileGrpId == null ? null : imgFileGrpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF002D.IMG_FILE_ID
     *
     * @return the value of TB_SAF002D.IMG_FILE_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getImgFileId() {
        return imgFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF002D.IMG_FILE_ID
     *
     * @param imgFileId the value for TB_SAF002D.IMG_FILE_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setImgFileId(String imgFileId) {
        this.imgFileId = imgFileId == null ? null : imgFileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF002D.FILE_NM
     *
     * @return the value of TB_SAF002D.FILE_NM
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getFileNm() {
        return fileNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF002D.FILE_NM
     *
     * @param fileNm the value for TB_SAF002D.FILE_NM
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setFileNm(String fileNm) {
        this.fileNm = fileNm == null ? null : fileNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF002D.FILE_EXT
     *
     * @return the value of TB_SAF002D.FILE_EXT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getFileExt() {
        return fileExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF002D.FILE_EXT
     *
     * @param fileExt the value for TB_SAF002D.FILE_EXT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setFileExt(String fileExt) {
        this.fileExt = fileExt == null ? null : fileExt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF002D.FILE_LENTH
     *
     * @return the value of TB_SAF002D.FILE_LENTH
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public Long getFileLenth() {
        return fileLenth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF002D.FILE_LENTH
     *
     * @param fileLenth the value for TB_SAF002D.FILE_LENTH
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setFileLenth(Long fileLenth) {
        this.fileLenth = fileLenth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF002D.FILE_PATH
     *
     * @return the value of TB_SAF002D.FILE_PATH
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF002D.FILE_PATH
     *
     * @param filePath the value for TB_SAF002D.FILE_PATH
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF002D.FILE_URL
     *
     * @return the value of TB_SAF002D.FILE_URL
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF002D.FILE_URL
     *
     * @param fileUrl the value for TB_SAF002D.FILE_URL
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF002D.THMNL_IMG_YN
     *
     * @return the value of TB_SAF002D.THMNL_IMG_YN
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getThmnlImgYn() {
        return thmnlImgYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF002D.THMNL_IMG_YN
     *
     * @param thmnlImgYn the value for TB_SAF002D.THMNL_IMG_YN
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setThmnlImgYn(String thmnlImgYn) {
        this.thmnlImgYn = thmnlImgYn == null ? null : thmnlImgYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF002D.SORT_SN
     *
     * @return the value of TB_SAF002D.SORT_SN
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public Long getSortSn() {
        return sortSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF002D.SORT_SN
     *
     * @param sortSn the value for TB_SAF002D.SORT_SN
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setSortSn(Long sortSn) {
        this.sortSn = sortSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF002D.REGIST_USR_ID
     *
     * @return the value of TB_SAF002D.REGIST_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getRegistUsrId() {
        return registUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF002D.REGIST_USR_ID
     *
     * @param registUsrId the value for TB_SAF002D.REGIST_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setRegistUsrId(String registUsrId) {
        this.registUsrId = registUsrId == null ? null : registUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF002D.REGIST_DT
     *
     * @return the value of TB_SAF002D.REGIST_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF002D.REGIST_DT
     *
     * @param registDt the value for TB_SAF002D.REGIST_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF002D.UPDT_USR_ID
     *
     * @return the value of TB_SAF002D.UPDT_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public String getUpdtUsrId() {
        return updtUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF002D.UPDT_USR_ID
     *
     * @param updtUsrId the value for TB_SAF002D.UPDT_USR_ID
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setUpdtUsrId(String updtUsrId) {
        this.updtUsrId = updtUsrId == null ? null : updtUsrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF002D.UPDT_DT
     *
     * @return the value of TB_SAF002D.UPDT_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public Date getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF002D.UPDT_DT
     *
     * @param updtDt the value for TB_SAF002D.UPDT_DT
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SAF002D.FILE_BLOB
     *
     * @return the value of TB_SAF002D.FILE_BLOB
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public byte[] getFileBlob() {
        return fileBlob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SAF002D.FILE_BLOB
     *
     * @param fileBlob the value for TB_SAF002D.FILE_BLOB
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    public void setFileBlob(byte[] fileBlob) {
        this.fileBlob = fileBlob;
    }
}