package com.merck.catalog.admin.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.merck.catalog.admin.vo.TbCab004d;

public interface TbCab004dMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB004D
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    int deleteByPrimaryKey(@Param("boardId") String boardId, @Param("postId") String postId, @Param("mangRegNo") String mangRegNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB004D
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    int insert(TbCab004d record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB004D
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    TbCab004d selectByPrimaryKey(@Param("boardId") String boardId, @Param("postId") String postId, @Param("mangRegNo") String mangRegNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB004D
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    List<TbCab004d> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CAB004D
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    int updateByPrimaryKey(TbCab004d record);
}