package com.merck.catalog.admin.dao;

import com.mybatis.gen.model.TbCbb001m;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbCbb001mMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CBB001M
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    int deleteByPrimaryKey(@Param("usrId") String usrId, @Param("boardId") String boardId, @Param("postId") String postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CBB001M
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    int insert(TbCbb001m record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CBB001M
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    TbCbb001m selectByPrimaryKey(@Param("usrId") String usrId, @Param("boardId") String boardId, @Param("postId") String postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CBB001M
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    List<TbCbb001m> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CBB001M
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    int updateByPrimaryKey(TbCbb001m record);
}