package com.merck.catalog.admin.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.merck.catalog.admin.vo.TbSaf002d;

public interface TbSaf002dMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAF002D
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    int deleteByPrimaryKey(@Param("imgFileGrpId") String imgFileGrpId, @Param("imgFileId") String imgFileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAF002D
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    int insert(TbSaf002d record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAF002D
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    TbSaf002d selectByPrimaryKey(@Param("imgFileGrpId") String imgFileGrpId, @Param("imgFileId") String imgFileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAF002D
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    List<TbSaf002d> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SAF002D
     *
     * @mbg.generated Wed Jul 28 11:31:26 KST 2021
     */
    int updateByPrimaryKey(TbSaf002d record);
}